# .github/workflows/fix-secret-labels.yml

name: Fix Missing AWSCURRENT Labels

on:
  workflow_dispatch: # Manual trigger only

jobs:
  fix-labels:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      AWS_REGION: eu-west-2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Fix AWSCURRENT labels on Viberoll secrets
        run: |
          echo "🔍 Scanning for viberoll-* secrets without AWSCURRENT label..."

          for secret in $(aws secretsmanager list-secrets \
            --region "$AWS_REGION" \
            --query "SecretList[?starts_with(Name, 'viberoll-')].Name" \
            --output text); do

            echo "🔐 Checking $secret"

            version_id=$(aws secretsmanager list-secret-version-ids \
              --secret-id "$secret" \
              --region "$AWS_REGION" \
              --query "Versions[-1].VersionId" \
              --output text)

            if [ "$version_id" = "None" ] || [ -z "$version_id" ]; then
              echo "⚠️  No version found for $secret — skipping"
              continue
            fi

            stages=$(aws secretsmanager describe-secret \
              --secret-id "$secret" \
              --region "$AWS_REGION" \
              --query "VersionIdsToStages.\"$version_id\"" \
              --output text)

            if [[ "$stages" != *AWSCURRENT* ]]; then
              echo "🚨 $secret is missing AWSCURRENT — assigning it now"
              aws secretsmanager update-secret-version-stage \
                --secret-id "$secret" \
                --region "$AWS_REGION" \
                --version-stage AWSCURRENT \
                --move-to-version-id "$version_id"
              echo "✅ AWSCURRENT set for $secret"
            else
              echo "✅ $secret already has AWSCURRENT"
            fi
          done
